#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
@File    :   Untitled-1
@Time    :   2023/04/12 10:36:37
@Author  :   Rico Chen 
@Version :   1.0
@Site    :   https://www.dgpms.cn/
@Desc    :   None
'''

# try:
#     import orson as json
# except ImportError:
#     try:
#         import simplejson as json
#     except ImportError:
#         import json
import pandas as pd
import os
import orjson
import utils


class data_utils():
    # def __init__(self, data_path):
    #     self.data_path = data_path
    
    def __init__(self):
        self.data_path = './html/'
        self.data = { "msg": "操作成功","total": 0,"code": "200","data": []}
 
    def to_dataframe(self):
        all_files = [os.path.join(root, file) for root, dirs, files in os.walk(self.data_path) for file in files if file.endswith('.json')]
         
        #data_list = [json.load(open(file)) for file in all_files]
        for file in all_files:
            f= open(file, "rb")   
            json_data = orjson.loads(f.read())
            #utils.json_data_merge(data,json_data)
            self.data["data"].extend(json_data["data"]) 
        df = pd.json_normalize(self.data, 'data',['msg','code'])
        df.to_excel("财政网-东莞.xlsx",encoding='utf-8')
        return df

a = data_utils()
a.data_path = './html/'
a.to_dataframe()