
    page.get_by_text("展开").click()
    page.locator("label").filter(has_text="工程监理").locator("span").nth(1).click()
    page.locator("label").filter(has_text="信息系统工程监理").locator("span").nth(1).click()
    page.locator("#serviceType").get_by_text("收起").click()
    page.get_by_placeholder("选取时间").click()
    page.get_by_role("cell", name="«").click()
    page.get_by_role("cell", name="今日").click()
    page.get_by_placeholder("选取时间").click()
    page.get_by_placeholder("至").click()
    page.get_by_role("cell", name="今日").click()
    page.get_by_placeholder("选取时间").click()
    page.get_by_placeholder("选取时间").fill("2021-1-1")
    page.locator("input[name=\"listVo\\.projectName\"]").click()
    page.get_by_placeholder("选取时间").click()
    page.get_by_role("cell", name="清除").click()
    page.get_by_placeholder("至").click()
    page.get_by_role("cell", name="清除").click()
    page.get_by_role("button", name="搜索").click()
    page.get_by_role("cell", name="东莞市东城水务工程运营中心").click()
    page.get_by_role("row", name="东莞市东城东部片区重点河涌补水系统完善工程监理服务 东莞市东城水务工程运营中心 工程监理 广州万安建设监理有限公司 2023-03-20").get_by_role("cell", name="工程监理", exact=True).click()
    page.get_by_role("cell", name="广州万安建设监理有限公司").click()
    page.get_by_role("row", name="东莞市东城东部片区重点河涌补水系统完善工程监理服务 东莞市东城水务工程运营中心 工程监理 广州万安建设监理有限公司 2023-03-20").get_by_role("cell", name="2023-03-20").click()
    page.get_by_role("cell", name="东莞市东城东部片区重点河涌补水系统完善工程监理服务").click()
    page.get_by_text("东莞市东城水务工程运营中心", exact=True).click()
    with page.expect_popup() as page1_info:
        page.get_by_role("link", name="东莞市东城东部片区重点河涌补水系统完善工程监理服务").click()
    page1 = page1_info.value
    page.get_by_text("暂不做评估与测算").click()
    page1.get_by_text("投资额（￥950,000.00元）").click()
    page.goto("https://ygp.gdzwfw.gov.cn/zjfwcs/gd-zjcs-pub/bidResultNotice")
    page2 = context.new_page()
    page2.goto("https://ygp.gdzwfw.gov.cn/zjfwcs/gd-zjcs-pub/bidResultNotice/view/4402810585615482303150272")
    page2.get_by_role("listitem").filter(has_text="服务金额： ￥30,000.00元").locator("div").click()
    page2.get_by_role("listitem").filter(has_text="中选金额： ￥30,000.00元").locator("div").click()
    page3 = context.new_page()
    page3.goto("https://ygp.gdzwfw.gov.cn/zjfwcs/gd-zjcs-pub/bidResultNotice/view/441302K305988112303150417")
    page3.locator("div").filter(has_text="广东三农工程技术有限公司").click()
    page3.close()
    page2.close()
    page1.close()
    page.locator("div").filter(has_text="广东省网上中介服务超市 Toggle navigation 项目业主登录 | 中介机构登录 超市首页 中介服务事项 中介服务机构 项目公告 评价中心 运营概况 ").get_by_role("link", name="超市首页").click()
    page.locator("div").filter(has_text="全类目 中介服务事项 中介服务机构 项目公告 评价中心 运营概况 通知公告 超市指南").get_by_role("link", name="项目公告").click()
    page.get_by_role("link", name="梅州中心城区污水处理效能提升建设工程（周溪河水质净化厂配套污水管网一期）地下管线探测服务").click()
    page.locator("div").filter(has_text="工程勘察").click()
    page.get_by_text("地下管线探测服务", exact=True).click()
    page.get_by_role("link", name="中选公告").click()
    page.get_by_role("link", name="惠州南站综合交通枢纽项目工程预算编制服务").click()
    with page.expect_popup() as page4_info:
        page.get_by_role("link", name="惠州南站综合交通枢纽项目工程预算编制服务").click()
    page4 = page4_info.value
    page4.get_by_text("2023-03-17 16:00", exact=True).click()
    page.get_by_text("我单位于2023-03-17 16:00， 在广东省网上中介服务超市为惠州市惠阳区人民政府淡水街道办事处公开选取工程造价咨询中介服务机构，现将中选结果相关事项公").click()
    page.goto("https://ygp.gdzwfw.gov.cn/zjfwcs/gd-zjcs-pub/bidResultNotice")
    page.get_by_role("link", name="小金口街道乌石村田心村民小组道路硬底化工程采购工程设计服务").click()
    page.get_by_text("该公司资质符合要求，综合评分高，业务能力强。").click()
    page.get_by_text("广州市天河区大观南路26号C203A").click()
    page.get_by_role("listitem").filter(has_text="中选金额： ￥12,100.00元").locator("div").click()
    page4.close()
    page.close()